### ISSUE TITLE
Display Human-Readable Memory Usage

### ISSUE THREAD

**Issue by AmeyaKhanzode** [acmpesuecc/Process-manager#2]
Current memory usage is shown in percentage, make it more understandable to display the memory usage in GB or MB.

**Comment by amankhandelwaal** [comment]
hi, please assign!

**Comment by jishnu-sivakumar** [comment]
can i try to solve this?

**Comment by AmeyaKhanzode** [comment]
!assign @Eggz2258

**Comment by AmeyaKhanzode** [comment]
!assign @Eggz2258

**Comment by AmeyaKhanzode** [comment]
you are assigned, you have 30 mins to solve it. if you are close please msg me to extend time

**Comment by Sami9692** [comment]
can u assign
?

**Comment by amankhandelwaal** [comment]
please assign

**Comment by AmeyaKhanzode** [comment]
someone is already working on the issue

**Comment by jishnu-sivakumar** [comment]
Can I have extended time, I just finished dinner

**Comment by amankhandelwaal** [comment]
hi, please assign!

**Comment by pushkar-gr** [comment]
@AmeyaKhanzode Can I get this ?

**Comment by jmanoj0905** [comment]
Can you please Assign this to me.

**Comment by AmeyaKhanzode** [comment]
!deassign @Eggz2258

**Comment by Shresht-Ahuja** [comment]
can i get assigned plspls

**Comment by jmanoj0905** [comment]
Can I get assigned please

**Comment by ghost** [comment]
assign me to this plz

**Comment by MeghanaK11** [comment]
Can I get assigned to this?

**Comment by pushkar-gr** [comment]
Can I get the issue
